### ISSUE TITLE
What pins and speed for connect on obd2

### ISSUE THREAD

**Issue by elshapovalov** [Trueffelwurm/MPi3#2]
Hi, tell me please.
What pins for connect on obd2 (6 and 14)?
And what speed use in raspbery config (125000)?

**Comment by JJToB** [comment]
Hi, on GM-Cars of that generation, Pin 3 is MS-CCAN low and 11 is high.
The Speed is 95000 bps.

**Comment by elshapovalov** [comment]
Thanks, it's really cool, but I can not get message from radio button volume (vol+ and vol-). Can you help me please?
