### ISSUE TITLE
How to.....

### ISSUE THREAD

**Issue by Arbe-GTC** [Trueffelwurm/MPi3#3]
Hi,
I'm trying running the code but always get some errors. You can share your RasPI image?
How to create the DB for the music?

The errors are related with some MODULES includes in the MPi3.py file (lines 59 to 68) how to install the necesary modules?

CAN works OK in my PI, i can send and recive via can using cansend can0 XXX#XXXXXXXXXXXX

I want to do the same, but i need to do proofs before install it in my Astra H . (CD70Navi + CID)

Thanks a lot.

**Comment by JJToB** [comment]
Hi!

I never expected than anyone else would actually try to use it. Nice to see
that!
What modules are you missing? I think most of the modules are installed by
default. Maybe you miss some packages like python-pygame an python-can?
Ich can export the list of installed packages on the raspberry when I am
back in my car.

**Comment by Arbe-GTC** [comment]
Hi! thanks for the answer. the project is very curious and interesting. I use some parts from Astra to do some proofs and obtain the CAN data to, for example, turn on the IPC, buttons, steering wheel buttons... And i want try your code. 

Some errors:

pi@canberry:~/Mp3PI$ sh scan.sh 
scan.sh: 12: scan.sh: [[: not found
scan.sh: 12: scan.sh: [[: not found
scan.sh: 12: scan.sh: [[: not found
scan.sh: 12: scan.sh: [[: not found
scan.sh: 21: scan.sh: [[: not found
scan.sh: 21: scan.sh: [[: not found
scan.sh: 21: scan.sh: [[: not found
scan.sh: 21: scan.sh: [[: not found
.
.
.
Error: near line 1: no such table: songs
Error: near line 2: no such table: songs
Error: near line 3: no such table: SONGS
Error: near line 4: no such table: songs
Error: near line 5: no such table: SONGS
Error: near line 6: no such table: songs
Error: near line 7: no such table: SONGS
Error: near line 8: no such table: songs
Error: near line 9: no such table: SONGS
Error: near line 70: no such table: songs
Error: near line 71: no such table: SONGS
Error: near line 72: no such table: disabled_songs
Error: near line 73: no such table: songs

pi@canberry:~/Mp3PI$ python3 MPi3.py
Traceback (most recent call last):
  File "MPi3.py", line 62, in <module>
    import stagger                                                                  # stagger for ID3 tags
ImportError: No module named 'stagger'


In scan.sh i edit this:
MUSIC_DIR=/home/pi/Mp3PI/music
DB=/home/pi/Mp3PI/music/mpi3.db

If you can help me, I would be greatly grateful.

i use this module: http://www.industrialberry.com/canberrydual-v2-1/

Thanks again :)

**Comment by Arbe-GTC** [comment]
Hi again. i installed OK the PYTHON-CAN folowing this: https://skpang.co.uk/blog/archives/1220 and stagger module

now i can send/recive canbus data via python3 succesfully.

If execute python3 MPi3.py i get this error

pi@canberry:~/Mp3PI$ python3 MPi3.py 
Traceback (most recent call last):
  File "MPi3.py", line 448, in <module>
    init_playround()                                                                # Get actual playround from db
  File "MPi3.py", line 301, in init_playround
    cursor.execute("SELECT max(playround) FROM `songs`;")                   # Query playround
sqlite3.OperationalError: no such table: songs

Maybe the problem is the sqlite file. its empty, no tables, no rows...

Thanks!

**Comment by Arbe-GTC** [comment]
Hi. Have you been able to check how to create the DB file? Or have you an script to generate de DB File?

**Comment by Arbe-GTC** [comment]
Solved! 
[mpi3.zip](https://github.com/Trueffelwurm/MPi3/files/4331700/mpi3.zip)
A friend has generated the file mpi3.db (sqlite) attached in ZIP, and works OK your code.

Thanks!
